### PR TITLE
moved buttons to top - not sticky

### PR DESCRIPTION
**Pull request by acholyn**
also made sure plots take 100% of the width

Related to https://github.com/UCL/UKCORDEX-plot-explorer/issues/54

### CODE REVIEW

**Comment by raquelalegre** [comment]
How do you feel about making the buttons wider so they show side by side taking the whole width? Like [these ones](https://react-bootstrap.netlify.app/components/buttons/#block-buttons) only side by side instead one on top of the other.

**Comment by raquelalegre** [comment]
I think the margins also need reviewing. The space between the buttons' area and the figure row is too small compared with the distance between the options row and the buttons.

**Review by raquelalegre — CHANGES_REQUESTED** [review]
Added a comment about the width of the buttons to make them stand out more, and the consistency of the margins between rows.

**Comment by acholyn** [comment]
> How do you feel about making the buttons wider so they show side by side taking the whole width? Like [these ones](https://react-bootstrap.netlify.app/components/buttons/#block-buttons) only side by side instead one on top of the other.

I'll try it out and show Claire to see what she thinks. I feel like it could look a bit weird but making them wider than they currently are sounds like a good idea.

**Review by raquelalegre — APPROVED** [review]

**Pull request merged**
