### PR TITLE
Forcing install temporarily so that we have working tests again.

### PR DESCRIPTION
**Pull request by raquelalegre**
I'm not proud of this one, but it's the quickest fix for now. I'll make an issue to investigate on the package.json dependencies so we don't need the `--force` flag.

### CODE REVIEW

**Comment by raquelalegre** [comment]
Changes include:
* Adding the `--force` flag to the install
* The CI env var is true by default in CI systems like GH Actions - this means the workflow will fail if there is a warning. I've changed it so it doesn't, and it only fails if there are errors. 
* Added the latest version of `package-lock.json` after a local install so synch with package.json.

**Comment by raquelalegre** [comment]
We should merge this soon, so that we can look into #67 and merge too soon, as that should be a straight forward change.

**Review by JamieJQuinn — CHANGES_REQUESTED** [review]
Can it be noted somewhere (an issue or in the code?) that this is temporary and should be reverted at some point?

**Comment by raquelalegre** [comment]
Yep, it's here: https://github.com/UCL/UKCORDEX-plot-explorer/issues/79. I'll add it to the code.

**Review by JamieJQuinn — APPROVED** [review]
Brilliant, thanks!

**Pull request merged**
