### PR TITLE
Updated project's icon

### LINKED ISSUE #19: Project logo
@clairbarnes mentions the Met Office might be able to help with this. That way we can replace the react logo that shows in the page, and maybe add it to the header/menu.

### PR DESCRIPTION
**Pull request by raquelalegre**
@yasna-palmeiro kindly provided a new project icon to replace the standard one.

Fixes https://github.com/UCL/UKCORDEX-plot-explorer/issues/19

### CODE REVIEW

**Comment by clairbarnes** [comment]
Looks great on the main page - but I noticed that the thumbnail is different in menus. I took a screenshot earlier (attached) but the latest dev version deployed is from a different branch, so the issue is no longer visible. It's a very minor thing but worth looking at in case it's an easy fix!

Screenshot_20220518-115352

**Comment by raquelalegre** [comment]
This is due to the size of the new icon. `manifest.json` points to the use of `logo512.png` or `logo192.png` when the size of the required icon is not suitable, and those were the default React logos that your are seeing @clairbarnes. So I have now :
* Replaced the default React logo pngs with @yasna-palmeiro's
* Added some padding to the default logo and centered the map so it is of a more regular size

**Comment by raquelalegre** [comment]
It now shows correctly on my bookmarks - how about yours @clairbarnes?

**Comment by clairbarnes** [comment]
This is now showing correctly in my bookmarks - will merge

**Review by clairbarnes — COMMENTED** [review]
Good to go

**Pull request merged**
